"""Shared configuration for the greeting example."""

DEFAULT_NAME = "World"
GREETING_TEMPLATE = "Hello, {name}!"
FAREWELL_TEMPLATE = "Goodbye, {name}!"
SHOUT_SUFFIX = "!!!"
WHISPER_PREFIX = "(psst) "
ECHO_REPEAT = 2
WAVE_SUFFIX = " o/"
CHEER_SUFFIX = " \\o/"
SIGH_SUFFIX = " ..."
CHUCKLE_SUFFIX = " heh"
GIGGLE_SUFFIX = " hehe~"
SNORT_SUFFIX = " pfft"
HUM_SUFFIX = " mmm~"
